//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDB.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_order_details
    {
        public int order_id { get; set; }
        public string item_name { get; set; }
        public int cat_id { get; set; }
        public System.DateTime order_date { get; set; }
        public int order_by_cust { get; set; }
        public bool isShipped { get; set; }
        public bool isDelivered { get; set; }
        public bool isActive { get; set; }
    
        public virtual t_category_master t_category_master { get; set; }
        public virtual T_user_details T_user_details { get; set; }
    }
}
