//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDB.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_user_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_user_details()
        {
            this.T_order_details = new HashSet<T_order_details>();
        }
    
        public int u_id { get; set; }
        public string u_name { get; set; }
        public System.DateTime u_dob { get; set; }
        public string u_city { get; set; }
        public bool Is_Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_order_details> T_order_details { get; set; }
    }
}
